[buildPlans.iosevka-sans-mono]
family = "Iosevka SansMono"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-sans-mono.variants.design]
capital-g = "toothless-corner-serifless-hooked"
capital-k = "symmetric-connected"
capital-q = "detached-bend-tailed"
capital-u = "toothless-rounded"
capital-r = "curly"
capital-w = "straight"
b = "toothless-corner"
c = "serifless"
f = "flat-hook"
g = "double-storey"
k = "symmetric-connected"
q = "earless-corner"
r = "compact-serifed"
t = "flat-hook"
y = "straight-turn"
zero = "dotted-oval"
one = "base-long-top-serif"
two = "straight-neck"
three = "flattop"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "bend-serifless"
eight = "two-circles"
nine = "open-contour"
asterisk = "hex-low"
underscore = "low"
caret = "medium"
#caret = "low"
bar = "force-upright"
percent = "rings-continuous-slash"
number-sign = "slanted"
ampersand = "closed"
dollar = "through"
cent = "through"
at = "fourfold"
lig-ltgteq = "flat"
#question = "corner-flat-hooked"
question = "smooth"

[buildPlans.iosevka-sans-mono.variants.italic]
f = "flat-hook-tailed"
g = "double-storey"
k = "cursive"
y = "straight-turn"
percent = "rings-continuous-slash-also-connected"

[buildPlans.iosevka-sans-mono.variants.oblique]
f = "flat-hook-extended"

  [buildPlans.iosevka-sans-mono.ligations]
  inherits = "dlig"
